apiVersion: v1
kind: Service

metadata:
    name: my-portfolio-service

spec:
    selector:
        app: my-portfolio

    ports:
      - protocol: TCP
        port: 9095
        targetPort: 9095

    type: LoadBalancer